version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: Hausaufgabe1
      POSTGRES_USER: ha1DBUser
      POSTGRES_PASSWORD: fweSS22
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
